[common]
bin = bin_03

[directory]
# Base paths
phd = /home/elom/phd
data = ${phd}/code
spectra = ${data}/spectra
models = ${data}/models

# Output directory
# Resolves to: /home/elom/phd/code/explanations/bin_03
explanations = ${data}/explanations/${common:bin}

[file]
spectra = spectra_anomalies.npy
wave = wave_spectra_imputed.npy
ids = specobjids_anomalies.npy

[score]
metric = mse
filter = 0
relative = False
percentage = 100
epsilon = 0.001

[lime]
segmentation = uniform
number_segments = 110
number_samples = 5000
batch_size = 100
progress_bar = False
distance_metric = cosine
number_features = 10000

[fudge]
kind_of_fudge = scale
scale_factor = 0.9
same_noise = True
kernel_size = 3
sigma = 0

[configuration]
seed = 42
jobs = 14
cores_per_worker = 1